/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/incremental-id-plugin.ts
var import_obsidian3 = require("obsidian");

// src/command-handler.ts
var CommandHandler = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  register() {
    this.plugin.configuration.configuration.idDefinitions.forEach((idDefinition) => {
      if (idDefinition.prefix) {
        this.add(null, idDefinition);
      }
    });
  }
  add(oldIdDefinition, newIdDefinition) {
    this.remove(oldIdDefinition);
    if (newIdDefinition) {
      this.plugin.addCommand({
        id: newIdDefinition.prefix,
        name: `Insert ${newIdDefinition.name}`,
        editorCallback: async (editor) => {
          const idDef = await this.plugin.configuration.getIncrementId(newIdDefinition.prefix);
          if (idDef) {
            const id = `${idDef.prefix}-${idDef.currentIteration}`;
            editor.replaceSelection(id);
          }
        }
      });
    }
  }
  remove(idDefinition) {
    if (idDefinition) {
      app.commands.removeCommand(this.getCommandId(idDefinition.prefix));
    }
  }
  getCommandId(prefix) {
    return `${this.plugin.manifest.id}:insert-id:${prefix}`;
  }
};

// src/settings/incremental-id-plugin-setting-tab.ts
var import_obsidian2 = require("obsidian");

// src/utils/index.ts
var import_obsidian = require("obsidian");
var Logger = class {
  static update(msg) {
    const notice = new import_obsidian.Notice("", 8e3);
    notice.noticeEl.innerHTML = `<b>Icremental Id Update</b>:<br/>${msg}`;
  }
  static error(e) {
    const notice = new import_obsidian.Notice("", 8e3);
    notice.noticeEl.innerHTML = `<b>Icremental Id Error</b>:<br/>${e.message}`;
  }
};

// src/settings/is-id-definition-valid.ts
var isIdDefinitionValid = (def, existingDefinitions) => {
  let invalid = false;
  if (def.name.length < 3 || existingDefinitions.find(({ name }) => name === def.name)) {
    Logger.error(new Error("You need provide unique name with at least 3 characters"));
    invalid = true;
  }
  if (def.prefix.length < 2 || !/^[A-Za-z0-9]*$/.test(def.prefix) || existingDefinitions.find(({ prefix }) => prefix === def.prefix)) {
    Logger.error(new Error("You need provide unique prefix from letters and numbers with at least 2 characters"));
    invalid = true;
  }
  if (!Number.isInteger(def.currentIteration) || def.currentIteration < 0) {
    Logger.error(new Error("You need provide positive integer or 0"));
    invalid = true;
  }
  return !invalid;
};

// src/settings/incremental-id-plugin-setting-tab.ts
var IncrementalIdPluginSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(plugin, config) {
    super(app, plugin);
    this.plugin = plugin;
    this.config = config;
  }
  addAddIdDefinitionSection() {
    let tempIdDefinition = {
      prefix: "",
      currentIteration: 0,
      name: ""
    };
    const s = new import_obsidian2.Setting(this.containerEl).addText((cb) => {
      cb.setPlaceholder("Provide name for your ID").setValue(tempIdDefinition.name).onChange(async (newIdName) => {
        tempIdDefinition.name = newIdName;
      });
    }).addText((cb) => {
      cb.setPlaceholder("Provide prefix for your ID, only uppercase letters allowed").setValue(tempIdDefinition.prefix).onChange(async (newPrefix) => {
        tempIdDefinition.prefix = newPrefix;
      });
    }).addText((cb) => {
      cb.setPlaceholder("Provide current iteration for your ID").setValue(tempIdDefinition.currentIteration.toString()).onChange(async (newIdIteration) => {
        tempIdDefinition.currentIteration = Number(newIdIteration);
      });
    }).addButton((cb) => {
      cb.setButtonText("Add new ID definition").setCta().onClick(async () => {
        if (!isIdDefinitionValid(tempIdDefinition, this.config.configuration.idDefinitions)) {
          return;
        }
        this.config.configuration.idDefinitions.push(tempIdDefinition);
        this.plugin.commandHandler.add(null, tempIdDefinition);
        tempIdDefinition = {
          prefix: "",
          currentIteration: 0,
          name: ""
        };
        await this.config.save();
        this.display();
      });
    });
    s.infoEl.remove();
  }
  addIdDefinitionSettingsSection() {
    this.containerEl.createEl("h2", { text: "Provide your IDs" });
    const desc = document.createDocumentFragment();
    desc.append("Particular IDs allow you to have a few separated IDs for different types of notes.");
    new import_obsidian2.Setting(this.containerEl).setDesc(desc);
    this.config.configuration.idDefinitions.forEach((idDefinition, index) => {
      const s = new import_obsidian2.Setting(this.containerEl).addText((cb) => {
        cb.setPlaceholder("Provide name for your ID").setValue(idDefinition.name).onChange(async (newIdName) => {
          if (newIdName && this.config.configuration.idDefinitions.find(({ name }) => name === newIdName)) {
            Logger.error(new Error("You need provide unique name"));
            return;
          }
          const updated = {
            ...this.config.configuration.idDefinitions[index],
            name: newIdName
          };
          this.plugin.commandHandler.add(this.config.configuration.idDefinitions[index], updated);
          this.config.configuration.idDefinitions[index] = updated;
          await this.config.save();
        });
      }).addText((cb) => cb.setDisabled(true).setValue(idDefinition.prefix)).addText((cb) => cb.setDisabled(true).setValue(idDefinition.currentIteration.toString())).addButton((cb) => {
        cb.setButtonText("Delete").setCta().onClick(async () => {
          this.config.configuration.idDefinitions.splice(index, 1);
          await this.config.save();
          this.plugin.commandHandler.remove(this.config.configuration.idDefinitions[index]);
          this.display();
        });
      });
      s.infoEl.remove();
    });
  }
  display() {
    this.containerEl.empty();
    this.addIdDefinitionSettingsSection();
    this.addAddIdDefinitionSection();
  }
};

// src/configuration/incremental-id-configuration.ts
var DEFAULT_CONFIGURATION = {
  idDefinitions: [
    {
      name: "Global ID",
      currentIteration: 0,
      prefix: "GUID"
    }
  ]
};
var IncrementalIdConfiguration = class _IncrementalIdConfiguration {
  constructor(plugin) {
    this.plugin = plugin;
  }
  static async create(plugin) {
    const instance = new _IncrementalIdConfiguration(plugin);
    instance.configuration = Object.assign({}, DEFAULT_CONFIGURATION, await instance._load());
    return instance;
  }
  async getIncrementId(aPrefix) {
    const index = this.configuration.idDefinitions.findIndex(({ prefix }) => prefix === aPrefix);
    if (index < 0) {
      Logger.error(new Error("Invalid ID prefix"));
      return;
    }
    this.configuration.idDefinitions[index].currentIteration++;
    await this.save();
    return this.configuration.idDefinitions[index];
  }
  async getCurrentId(aPrefix) {
    const index = this.configuration.idDefinitions.findIndex(({ prefix }) => prefix === aPrefix);
    if (index < 0) {
      Logger.error(new Error("Invalid ID prefix"));
      return;
    }
    return this.configuration.idDefinitions[index];
  }
  async save() {
    await this._save(this.configuration);
  }
  async _save(data) {
    await this.plugin.saveData(data);
  }
  _load() {
    return this.plugin.loadData();
  }
};

// src/incremental-id-plugin.ts
var IncrementalIdPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadConfiguration();
    this.addSettingTab(new IncrementalIdPluginSettingTab(this, this.configuration));
    app.insertIncrementalId = async (prefix) => {
      const idDef = await this.configuration.getIncrementId(prefix);
      if (idDef) {
        return `${idDef.prefix}-${idDef.currentIteration}`;
      }
    };
    app.insertCurrentIncrementalId = async (prefix) => {
      const idDef = await this.configuration.getCurrentId(prefix);
      if (idDef) {
        return `${idDef.prefix}-${idDef.currentIteration}`;
      }
    };
  }
  onunload() {
    app.insertIncrementalId = void 0;
  }
  async loadConfiguration() {
    this.configuration = await IncrementalIdConfiguration.create(this);
    this.commandHandler = new CommandHandler(this);
    this.commandHandler.register();
  }
};

// src/main.ts
var main_default = IncrementalIdPlugin;
